---
language: go

sudo: required
dist: trusty

services:
- docker

go:
- 1.6

before_script:
- go vet

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- sudo apt-get install fuse

install:
- make keywhiz-fs
- docker build -t square/keywhiz-fs .

before_script:
- sudo chmod 644 /etc/fuse.conf
- echo "user_allow_other" | sudo tee -a /etc/fuse.conf

script:
- make test
- make integration-test

after_success:
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
