language: go

sudo: required
dist: trusty

services:
- docker

go:
- 1.6

before_script:
- go vet

before_install:
- go get github.com/Masterminds/glide
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- sudo apt-get install fuse

install:
- make build
- docker build -t square/keywhiz-fs .

script:
- make test

after_success:
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
