language: go

sudo: true

env:
- GO15VENDOREXPERIMENT=1

matrix:
  allow_failures:
    - go: tip

go:
- 1.5
- tip

before_script:
- go vet

before_install:
- go get github.com/Masterminds/glide
- make depends

install:
- make build
- sudo apt-get install fuse-utils
# This is to properly get fusermount on travis

script:
- go test -v .
